create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  main_numbers jsonb not null,
  bonus_number integer not null,
  created_at timestamptz not null default now()
);

alter table public.lotto_draws enable row level security;

drop policy if exists "Allow read lotto draws" on public.lotto_draws;
create policy "Allow read lotto draws"
on public.lotto_draws
for select
using (true);

drop policy if exists "Allow insert lotto draws" on public.lotto_draws;
create policy "Allow insert lotto draws"
on public.lotto_draws
for insert
with check (true);
